import fs from 'fs';
import path from 'path';
import { Ad, AdCategory } from '../types/ad';
import { CompetitorAnalysis, ExecutiveSummary, StrategicOpportunity } from '../types/analysis';
import { createLogger } from '../utils/logger';

const logger = createLogger('html-reporter');

export interface HtmlReportOptions {
  outputDir: string;
  filename?: string;
  includeCharts?: boolean;
}

export class HtmlReporter {
  private options: HtmlReportOptions;

  constructor(options: HtmlReportOptions) {
    this.options = {
      includeCharts: true,
      ...options
    };
  }

  generate(
    competitor: string,
    ads: Ad[],
    analysis: CompetitorAnalysis,
    summary?: ExecutiveSummary
  ): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Competitive Ad Analysis: ${this.escapeHtml(competitor)}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    body { font-family: 'Inter', system-ui, sans-serif; }
    .gradient-header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
    .stat-card { transition: transform 0.2s ease; }
    .stat-card:hover { transform: translateY(-2px); }
    .progress-bar { background: linear-gradient(90deg, #667eea, #764ba2); }
    .ad-card { border-left: 4px solid #667eea; }
    @media print {
      .no-print { display: none; }
      .page-break { page-break-after: always; }
    }
  </style>
</head>
<body class="bg-gray-50 min-h-screen">
  <!-- Header -->
  <header class="gradient-header text-white py-12 px-6">
    <div class="max-w-6xl mx-auto">
      <div class="flex items-center justify-between mb-4">
        <span class="text-sm font-medium opacity-75">Competitive Intelligence Report</span>
        <span class="text-sm opacity-75">${new Date(analysis.analysisDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
      </div>
      <h1 class="text-4xl font-bold mb-2">${this.escapeHtml(competitor)}</h1>
      <p class="text-xl opacity-90">Ad Library Analysis & Strategic Insights</p>
    </div>
  </header>

  <main class="max-w-6xl mx-auto px-6 py-8">
    <!-- Quick Stats -->
    ${this.renderQuickStats(analysis)}

    <!-- Executive Summary -->
    ${summary ? this.renderExecutiveSummary(summary) : ''}

    <!-- Platform Distribution -->
    ${this.renderPlatformDistribution(analysis)}

    <!-- Category Breakdown -->
    ${this.renderCategoryBreakdown(analysis)}

    <!-- Messaging Analysis -->
    ${this.renderMessagingAnalysis(analysis)}

    <!-- CTA Analysis -->
    ${this.renderCTAAnalysis(analysis)}

    <!-- Sample Ads -->
    ${this.renderSampleAds(ads, analysis)}

    <!-- Strategic Opportunities -->
    ${summary?.strategicOpportunities ? this.renderOpportunities(summary.strategicOpportunities) : ''}

    <!-- Recommended Actions -->
    ${summary?.recommendedActions ? this.renderRecommendations(summary.recommendedActions) : ''}
  </main>

  <!-- Footer -->
  <footer class="bg-gray-800 text-gray-400 py-8 px-6 mt-12">
    <div class="max-w-6xl mx-auto text-center">
      <p class="text-sm">Generated by Competitive Ads Extractor</p>
      <p class="text-xs mt-1 opacity-75">Analysis performed on ${new Date().toISOString()}</p>
    </div>
  </footer>
</body>
</html>`;
  }

  async save(
    competitor: string,
    ads: Ad[],
    analysis: CompetitorAnalysis,
    summary?: ExecutiveSummary
  ): Promise<string> {
    const html = this.generate(competitor, ads, analysis, summary);

    if (!fs.existsSync(this.options.outputDir)) {
      fs.mkdirSync(this.options.outputDir, { recursive: true });
    }

    const filename = this.options.filename || this.generateFilename(competitor);
    const filepath = path.join(this.options.outputDir, filename);

    fs.writeFileSync(filepath, html, 'utf-8');
    logger.info(`HTML report saved: ${filepath}`);

    return filepath;
  }

  private generateFilename(competitor: string): string {
    const sanitized = competitor.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    const timestamp = new Date().toISOString().split('T')[0];
    return `${sanitized}_${timestamp}.html`;
  }

  private renderQuickStats(analysis: CompetitorAnalysis): string {
    const stats = [
      { label: 'Total Ads', value: analysis.totalAds.toString(), icon: '📊' },
      { label: 'Platforms', value: Object.keys(analysis.platformBreakdown).length.toString(), icon: '📱' },
      { label: 'Avg Length', value: `${analysis.copyAnalysis.avgCopyLength} chars`, icon: '📝' },
      { label: 'Readability', value: `${analysis.copyAnalysis.readabilityScore}/100`, icon: '📖' }
    ];

    return `
    <section class="grid grid-cols-2 md:grid-cols-4 gap-4 -mt-8 mb-8">
      ${stats.map(stat => `
        <div class="stat-card bg-white rounded-lg shadow-lg p-6 text-center">
          <span class="text-2xl mb-2 block">${stat.icon}</span>
          <div class="text-3xl font-bold text-gray-800">${stat.value}</div>
          <div class="text-sm text-gray-500 mt-1">${stat.label}</div>
        </div>
      `).join('')}
    </section>`;
  }

  private renderExecutiveSummary(summary: ExecutiveSummary): string {
    return `
    <section class="bg-white rounded-lg shadow-lg p-6 mb-8">
      <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
        <span class="mr-2">📋</span> Executive Summary
      </h2>
      <div class="prose max-w-none">
        <p class="text-gray-600 text-lg leading-relaxed mb-4">${this.escapeHtml(summary.keyFindings.summary)}</p>
        <div class="grid md:grid-cols-2 gap-4 mt-6">
          <div class="bg-indigo-50 rounded-lg p-4">
            <div class="text-sm font-medium text-indigo-600 mb-1">Primary Theme</div>
            <div class="text-lg font-semibold text-gray-800">${this.escapeHtml(summary.keyFindings.primaryTheme)}</div>
          </div>
          <div class="bg-green-50 rounded-lg p-4">
            <div class="text-sm font-medium text-green-600 mb-1">Key Opportunity</div>
            <div class="text-lg font-semibold text-gray-800">${this.escapeHtml(summary.keyFindings.keyOpportunity)}</div>
          </div>
        </div>
      </div>
    </section>`;
  }

  private renderPlatformDistribution(analysis: CompetitorAnalysis): string {
    const total = Object.values(analysis.platformBreakdown).reduce((a, b) => a + b, 0);
    const platforms = Object.entries(analysis.platformBreakdown)
      .sort((a, b) => b[1] - a[1]);

    return `
    <section class="bg-white rounded-lg shadow-lg p-6 mb-8">
      <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
        <span class="mr-2">📱</span> Platform Distribution
      </h2>
      <div class="space-y-4">
        ${platforms.map(([platform, count]) => {
          const pct = Math.round((count / total) * 100);
          return `
          <div class="flex items-center">
            <div class="w-24 font-medium text-gray-700">${this.escapeHtml(platform)}</div>
            <div class="flex-1 mx-4">
              <div class="h-6 bg-gray-200 rounded-full overflow-hidden">
                <div class="h-full progress-bar rounded-full" style="width: ${pct}%"></div>
              </div>
            </div>
            <div class="w-16 text-right text-gray-600">${count} (${pct}%)</div>
          </div>`;
        }).join('')}
      </div>
    </section>`;
  }

  private renderCategoryBreakdown(analysis: CompetitorAnalysis): string {
    const total = Object.values(analysis.categoryBreakdown).reduce((a, b) => a + b, 0);
    const categories = Object.entries(analysis.categoryBreakdown)
      .filter(([_, count]) => count > 0)
      .sort((a, b) => b[1] - a[1]);

    const colors = ['bg-indigo-500', 'bg-purple-500', 'bg-pink-500', 'bg-red-500', 'bg-orange-500', 'bg-yellow-500'];

    return `
    <section class="bg-white rounded-lg shadow-lg p-6 mb-8">
      <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
        <span class="mr-2">📊</span> Ad Categories
      </h2>
      <div class="grid md:grid-cols-2 gap-4">
        ${categories.map(([category, count], i) => {
          const pct = Math.round((count / total) * 100);
          return `
          <div class="flex items-center p-3 rounded-lg hover:bg-gray-50">
            <div class="w-3 h-3 rounded-full ${colors[i % colors.length]} mr-3"></div>
            <div class="flex-1">
              <div class="font-medium text-gray-800">${this.formatCategoryName(category)}</div>
              <div class="text-sm text-gray-500">${count} ads</div>
            </div>
            <div class="text-2xl font-bold text-gray-700">${pct}%</div>
          </div>`;
        }).join('')}
      </div>
    </section>`;
  }

  private renderMessagingAnalysis(analysis: CompetitorAnalysis): string {
    const topKeywords = analysis.copyAnalysis.topKeywords.slice(0, 15);
    const topPhrases = analysis.copyAnalysis.commonPhrases.slice(0, 8);
    const topHashtags = Array.from(analysis.copyAnalysis.hashtagFrequency.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10);

    return `
    <section class="bg-white rounded-lg shadow-lg p-6 mb-8">
      <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
        <span class="mr-2">💬</span> Messaging Analysis
      </h2>

      <div class="grid md:grid-cols-2 gap-6">
        <!-- Keywords -->
        <div>
          <h3 class="font-semibold text-gray-700 mb-3">Top Keywords</h3>
          <div class="flex flex-wrap gap-2">
            ${topKeywords.map((kw, i) => `
              <span class="px-3 py-1 rounded-full text-sm font-medium ${i < 5 ? 'bg-indigo-100 text-indigo-700' : 'bg-gray-100 text-gray-600'}">
                ${this.escapeHtml(kw)}
              </span>
            `).join('')}
          </div>
        </div>

        <!-- Themes -->
        <div>
          <h3 class="font-semibold text-gray-700 mb-3">Messaging Themes</h3>
          <div class="space-y-2">
            ${analysis.messagingThemes.slice(0, 5).map(theme => `
              <div class="flex items-center">
                <span class="w-2 h-2 bg-purple-500 rounded-full mr-2"></span>
                <span class="text-gray-600">${this.escapeHtml(theme)}</span>
              </div>
            `).join('')}
          </div>
        </div>
      </div>

      <!-- Common Phrases -->
      <div class="mt-6">
        <h3 class="font-semibold text-gray-700 mb-3">Common Phrases</h3>
        <div class="grid md:grid-cols-2 gap-2">
          ${topPhrases.map(phrase => `
            <div class="bg-gray-50 rounded px-3 py-2 text-gray-600 text-sm">
              "${this.escapeHtml(phrase)}"
            </div>
          `).join('')}
        </div>
      </div>

      ${topHashtags.length > 0 ? `
      <!-- Hashtags -->
      <div class="mt-6">
        <h3 class="font-semibold text-gray-700 mb-3">Top Hashtags</h3>
        <div class="flex flex-wrap gap-2">
          ${topHashtags.map(([tag, count]) => `
            <span class="px-3 py-1 bg-blue-50 text-blue-600 rounded-full text-sm">
              ${this.escapeHtml(tag)} <span class="text-blue-400">(${count})</span>
            </span>
          `).join('')}
        </div>
      </div>
      ` : ''}
    </section>`;
  }

  private renderCTAAnalysis(analysis: CompetitorAnalysis): string {
    const ctas = analysis.ctaPatterns.slice(0, 8);

    return `
    <section class="bg-white rounded-lg shadow-lg p-6 mb-8">
      <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
        <span class="mr-2">🎯</span> Call-to-Action Analysis
      </h2>
      <div class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="text-left text-gray-500 text-sm border-b">
              <th class="pb-3 font-medium">CTA Text</th>
              <th class="pb-3 font-medium text-center">Count</th>
              <th class="pb-3 font-medium text-center">Usage %</th>
              <th class="pb-3 font-medium">Distribution</th>
            </tr>
          </thead>
          <tbody>
            ${ctas.map(({ cta, count, percentage }) => `
              <tr class="border-b border-gray-100">
                <td class="py-3 font-medium text-gray-800">${this.escapeHtml(cta)}</td>
                <td class="py-3 text-center text-gray-600">${count}</td>
                <td class="py-3 text-center text-gray-600">${percentage}%</td>
                <td class="py-3">
                  <div class="h-2 bg-gray-200 rounded-full w-32">
                    <div class="h-full progress-bar rounded-full" style="width: ${percentage}%"></div>
                  </div>
                </td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
    </section>`;
  }

  private renderSampleAds(ads: Ad[], analysis: CompetitorAnalysis): string {
    const adsByCategory = new Map<AdCategory, Ad[]>();
    for (const ad of ads) {
      if (ad.category) {
        const existing = adsByCategory.get(ad.category) || [];
        existing.push(ad);
        adsByCategory.set(ad.category, existing);
      }
    }

    const sortedCategories = Object.entries(analysis.categoryBreakdown)
      .filter(([_, count]) => count > 0)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 4);

    return `
    <section class="bg-white rounded-lg shadow-lg p-6 mb-8">
      <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
        <span class="mr-2">📄</span> Sample Ads
      </h2>

      ${sortedCategories.map(([category]) => {
        const categoryAds = adsByCategory.get(category as AdCategory) || [];
        const sampleAds = categoryAds.slice(0, 3);
        if (sampleAds.length === 0) return '';

        return `
        <div class="mb-6">
          <h3 class="font-semibold text-gray-700 mb-3">${this.formatCategoryName(category)}</h3>
          <div class="space-y-4">
            ${sampleAds.map(ad => this.renderAdCard(ad)).join('')}
          </div>
        </div>`;
      }).join('')}
    </section>`;
  }

  private renderAdCard(ad: Ad): string {
    const text = ad.primaryText?.length > 250
      ? ad.primaryText.substring(0, 250) + '...'
      : ad.primaryText || '';

    return `
    <div class="ad-card bg-gray-50 rounded-lg p-4">
      <p class="text-gray-700 italic mb-3">"${this.escapeHtml(text)}"</p>
      <div class="flex flex-wrap gap-3 text-sm text-gray-500">
        ${ad.cta ? `<span class="bg-indigo-100 text-indigo-700 px-2 py-1 rounded">CTA: ${this.escapeHtml(ad.cta)}</span>` : ''}
        ${ad.platforms?.length ? `<span>📱 ${ad.platforms.join(', ')}</span>` : ''}
        ${ad.startDate ? `<span>📅 ${ad.startDate}</span>` : ''}
      </div>
    </div>`;
  }

  private renderOpportunities(opportunities: StrategicOpportunity[]): string {
    const priorityStyles = {
      high: { bg: 'bg-red-50', border: 'border-red-200', icon: '🔴', text: 'text-red-700' },
      medium: { bg: 'bg-yellow-50', border: 'border-yellow-200', icon: '🟡', text: 'text-yellow-700' },
      low: { bg: 'bg-green-50', border: 'border-green-200', icon: '🟢', text: 'text-green-700' }
    };

    return `
    <section class="bg-white rounded-lg shadow-lg p-6 mb-8">
      <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
        <span class="mr-2">💡</span> Strategic Opportunities
      </h2>
      <div class="space-y-4">
        ${opportunities.map(opp => {
          const style = priorityStyles[opp.priority];
          return `
          <div class="${style.bg} border ${style.border} rounded-lg p-4">
            <div class="flex items-start">
              <span class="mr-3 text-lg">${style.icon}</span>
              <div>
                <div class="font-semibold text-gray-800">${this.escapeHtml(opp.description)}</div>
                <div class="${style.text} mt-1">${this.escapeHtml(opp.opportunity)}</div>
                <span class="inline-block mt-2 text-xs uppercase tracking-wide ${style.text} font-medium">${opp.type}</span>
              </div>
            </div>
          </div>`;
        }).join('')}
      </div>
    </section>`;
  }

  private renderRecommendations(recommendations: string[]): string {
    return `
    <section class="bg-gradient-to-r from-indigo-500 to-purple-600 rounded-lg shadow-lg p-6 mb-8 text-white">
      <h2 class="text-2xl font-bold mb-4 flex items-center">
        <span class="mr-2">🎯</span> Recommended Actions
      </h2>
      <div class="space-y-3">
        ${recommendations.map((rec, i) => `
          <div class="flex items-start">
            <span class="flex-shrink-0 w-8 h-8 bg-white/20 rounded-full flex items-center justify-center font-bold mr-3">${i + 1}</span>
            <p class="text-white/90 leading-relaxed">${this.escapeHtml(rec)}</p>
          </div>
        `).join('')}
      </div>
    </section>`;
  }

  private formatCategoryName(category: string): string {
    return category
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
}

export function generateHtmlReport(
  competitor: string,
  ads: Ad[],
  analysis: CompetitorAnalysis,
  outputDir: string
): Promise<string> {
  const reporter = new HtmlReporter({ outputDir });
  return reporter.save(competitor, ads, analysis);
}
